- Programs/Rohan Das/TRAVELPS/ProblemStatement.md
- Programs/Rohan Das/TRAVELPS/Solution.c++
I've added the code of the problem TRAVELPS which was asked in SEPTEMBER LONG CHALLEGE
> TRAVELPS Solution Added

- Programs/inverse_of_a_3x3_matrix.cpp
Added a program to find Inverse of 3x3 matrix.
> Added a program to find Inverse of Matrix

- Projects/camera.py
I added a basic camera application using kivy and cv2 in python . Please review it :)
> Added Camera.py

- Programs/hrishik18/ProblemStatement.md
- Programs/hrishik18/Solution.cpp
This Codechef is from Starters 07
> Added the Solution of codechef problem MAXARXOR

- Programs/Chayan Debbarma/C codes/Generating Multiplication Table using DMA.c
Added a c code to generate multiplication table using Dynamic Memory Allocation
> Generating Multiplication Table using DMA.c

- Programs/Tanmay Kulkarni/BinarySearch.cpp
- Programs/Tanmay Kulkarni/Problem description.md
Hey, i've added a binary search implementation pgm in c++ using recursion.
proper description & documentation is also provided! 
Pls, review the commits or merge it accordingly! #Hacktoberfest2021
> Binary search implementation!

- Programs/aneesh/SPCTRIPS.cpp
- Programs/aneesh/problem statement.md
Added the Solution of codechef problem SPCTRIPS
>  Added the Solution of codechef problem SPCTRIPS

- Programs/Preksha/Problem Statement (from Hackerrank).txt
- Programs/Preksha/Solution.py
Hey! I have solved a Hackerrank Problem - Finding the Percentages, using Python.
> First Program

- Projects/ParamTatiya02(A.I assistant using python libraries)/Readme.md
- Projects/ParamTatiya02(A.I assistant using python libraries)/jarvis.py
A python project named "Jarvis" which is a simple AI assistant ,made with python libraries
> Added a simple python project

- Programs/mayuri/Basic linked list.c
hello mam i just added the code in c to create basic linked list. Please review and merge it @akanksha-raghav .
> Update Basic linked list.c

- Projects/resume_builder using vanilla js/index.html
- Projects/resume_builder using vanilla js/readme.md
- Projects/resume_builder using vanilla js/script.js
- Projects/resume_builder using vanilla js/style.css
I have added a resume builder program with some awesome features in the project folder
features :-
1)it is professionally designed 
2)sections can be added dynamically
3)resume can be edited as per need
4)the resume can be downloaded in pdf format after editing is over
> resume builder added

- Projects/connectfour/METADATA
- Projects/connectfour/connectFour.js
- Projects/connectfour/connectFour.kif
- Projects/connectfour/connectFour.txt
- Projects/connectfour/connectFour.xsl
Connect 4 games in GDL language.
> GDL Project

- Projects/Background-generator/index.css
- Projects/Background-generator/index.html
- Projects/Background-generator/sc.js
"Created a background generator"
> Added Background-generator

- Programs/Amandeep/ClimbingStairs.cpp
- Programs/Amandeep/Coin Changing Problem.cpp
- Programs/Amandeep/DifferentWaysToAddParenthesis.cpp
- Programs/Amandeep/Knapsack_Memoization.cpp
- Programs/Amandeep/Knapsack_Recursive.cpp
- Programs/Amandeep/Knapsack_bottom_up.cpp
- Programs/Amandeep/MCM_MEMOIZATION.cpp
- Programs/Amandeep/MCM_RECURSIVE.cpp
- Programs/Amandeep/minEditDistance.cpp
Added Standard Questions of DP well-commented
> DP Standard Programs

- Projects/Supr3me-code/snank-game.py
Snake game using Tkinter python library
> Snake Game

- Projects/Keylogger/linux_keylogger.py
- Projects/Keylogger/windows_keylogger.py
Keylogger for windows and Linux. made in python
> Created Keylogger

- Find X Quadratic Equation.py
Used to find x1 and x2 for a quadratic equation
> Added Quadratic Equation Solver

- Projects/DSA implementation using C/CircularQueue.c
- Projects/DSA implementation using C/DoublyLinkedList.c
- Projects/DSA implementation using C/PolynomialCalculation.c
- Projects/DSA implementation using C/Queue from stack.c
- Projects/DSA implementation using C/SingleLinkedList.c
- Projects/DSA implementation using C/Stacks.c
- Projects/DSA implementation using C/readme.md
- Projects/DSA implementation using C/sparsematrix.c
Please mark this as hacktober fest accpeted!
> DSA implementations using C

- Projects/calculator.py
Implemented a calculator GUI using python's Tkinter library
> Calculator

- Programs/calculatorAdvance.cpp
Added a calculator program in `program` folder, which asks user to perform certain operations on the entered numbers untill the user wants to exits.
> Added a Calculator program (CPP) 
